name: face_camera
description: Developed by mouhib sahbani originally from https://github.com/Conezi/face_camera
version: 0.0.1


environment:
  sdk: '>=2.18.4 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.1

flutter:

  plugin:
    platforms:
      android:
        package: com.mouhib.face_camera
        pluginClass: FaceCameraPlugin
      ios:
        pluginClass: FaceCameraPlugin